language: sh

install:
  - curl -L https://deno.land/x/install/install.sh | sh -s v0.3.10
  - export PATH="$HOME/.deno/bin:$PATH"

script:
  - deno --version
  - deno --allow-net --allow-read -r test.ts

cache:
  directories:
    - '$HOME/.deno'
